#!/bin/bash

if [ "$#" -lt 1 ]; then
	echo "Illegal number of parameters"
	exit
fi

# loop arxeiwn
for file in $*
do

	# arxikopoihseis gia ka8e arxeio
	length=0
	sum_x=0
	sum_y=0
	sum_xy=0
	sum_x2=0
	err=0
	flag=1

	# pairnei mia grammh ana epanalipsh
	for line in `cat ${file}`
	do

		X[length]=$(cut -d':' -f1 <<<${line}) # pairnei prin to delimeter
		Y[length]=$(cut -d':' -f2 <<<${line}) # pairnei to ipoloipo
		
		# xrhsimopoioume ekswteriko ergaleio(awk) gia pros8esh floats
		# to bc eixe kakh akribeia fp
		sum_x=$(awk "BEGIN {print ${sum_x} + ${X[length]}; exit}")
		sum_y=$(awk "BEGIN {print ${sum_y} + ${Y[length]}; exit}")
		sum_xy=$(awk "BEGIN {print ${sum_xy} + ${X[length]} * ${Y[length]}; exit}")
		sum_x2=$(awk "BEGIN {print ${sum_x2} + ${X[length]} * ${X[length]}; exit}")

		# elenxos gia sta8ero dianusma
		if (( $(awk "BEGIN {print (${X[0]} != ${X[length]})}") ))
		then
			flag=0
		fi

		let "length = length + 1"	# ari8mos seirwn arxeiou
	done

	# an to dianusma einai sta8ero o paranomasths tou a 8a ginei mhden kai den mporei na ginei h diairesh.
	# xrhsimopoioume ton tupo ax = cy + b. Epeidh ola ta shmeia einai se ka8eth eu8eia c=0, err=0 kai b=X[0].
	# to a leitourgei opws to c sthn synarthsh cy = ax + b
	if [ ${flag} -ne 0 ]
	then
		a=1
		c=0
		b=${X[0]}
		err=0

	# kanonikes periptwseis
	else
		a_ari8mhths=$(awk "BEGIN {print ${length} * ${sum_xy} - ${sum_x} * ${sum_y}; exit}")
		a_paranomasths=$(awk "BEGIN {print ${length} * ${sum_x2} - ${sum_x} * ${sum_x}; exit}")
		a=$(awk "BEGIN {print ${a_ari8mhths} / ${a_paranomasths}; exit}")
		b=$(awk "BEGIN {print (${sum_y} - ${a} * ${sum_x}) / ${length}; exit}")
		c=1

		for ((i=0; i < ${length}; i++))
		do
			err=$(awk "BEGIN {print ${err} + ((${Y[i]} - (${a} * ${X[i]} + ${b})) ^ 2); exit}")
		done
	fi

	echo -n "FILE: $file, a="
	# xrhsimopoioume thn printf gia thn stroggulopoihsh. 
	# allazoume to locale gia na balei "." anti "," ean to LC tou leitourgikou einai sta ellhnika
	a=`LC_ALL=C printf "%0.2f" $a`
	# to awk kobei trailing zeroes kai "." an den xreiazontai, to tr kobei ta \n tou print gia na exei to format ths ekfwnhshs
	echo $a | awk ' { sub("0+$",""); sub("\\.$",""); print} ' | tr '\n' ' '

	echo -n "b="
	b=`LC_ALL=C printf "%0.2f" $b`
	echo $b | awk ' { sub("0+$",""); sub("\\.$",""); print} ' | tr '\n' ' '

	echo -n "c=${c} err="
	err=`LC_ALL=C printf "%0.2f" $err`
	echo $err | awk ' { sub("0+$",""); sub("\\.$",""); print} '

done

exit